DIRS += $(CURDIR)/uecho

INCLUDES += -I$(CURDIR)/uecho \
			-I$(OPENWSN_ROOT)/openstack/04-TRAN \
			-I$(OPENWSN_ROOT)/openstack/03b-IPv6 \
			-I$(OPENWSN_ROOT)/openstack/03a-IPHC \
			-I$(OPENWSN_ROOT)/openstack/02b-MAChigh \
			-I$(OPENWSN_ROOT)/openstack/02a-MAClow \
			-I$(OPENWSN_ROOT)/openstack/cross-layers

include $(RIOTBASE)/Makefile.base
