#MODULE = openwsn

DIRS +=02a-MAClow
DIRS +=02b-MAChigh
DIRS +=03a-IPHC
DIRS +=03b-IPv6
DIRS +=04-TRAN
DIRS +=cross-layers

INCLUDES += -I$(CURDIR)/../drivers/common \
			-I$(CURDIR)/02a-MAClow \
			-I$(CURDIR)/02b-MAChigh \
			-I$(CURDIR)/03a-IPHC \
			-I$(CURDIR)/03b-IPv6 \
			-I$(CURDIR)/04-TRAN \
			-I$(CURDIR)/cross-layers

# CFLAGS += -DDAGROOT

include $(RIOTBASE)/Makefile.base
